### ISSUE TITLE
Issue: Won't connect through to head unit

### ISSUE THREAD

**Issue by tallLeRoy** [Snirpo/aawireless-issues#1]
**Describe the bug**
Phone connects to AAWireless device using Bluetooth and WiFi, but head unit does not recognize that Android Auto is present. 

**Screenshots**
none

**Car (please complete the following information):**
 - Manufacturer 2020 Hyundai Palisade 

**Headunit (please complete the following information):**
 - Manufacturer Hyundai 10.25 inch Navigation Infortainment system software version 14.0

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - Android version 10

**Additional context**
Things go well except the head unit does not 'see' Android Auto on the usb port.

**Comment by borconi** [comment]
Will provide a new image tomorrow, with verbose logging enabled so we can see what's happening.

- On the phone did you actually get stuck in "looking for Android Auto" or did it switched to "Connected to Android Auto"?
- Have you tried a different USB-C cable for the board?

**Comment by tallLeRoy** [comment]
I see both 'Connected to Android Auto' which goes away after a while and 'Looking for Android Auto' which stays around.

Yes, I have tried three different USB-A to USB-C cables. All of which work with these phones USB connected.

**Comment by tallLeRoy** [comment]
Here is a smaller log file. This is just the Samsung phone attempt. Followed by taking it into the house and using a power supply to get the log over ssh.
[JustTheSamsung-aawireless.log](https://github.com/Snirpo/aawireless-issues/files/5081360/JustTheSamsung-aawireless.log)

**Comment by borconi** [comment]
Could you please confirm the BT mac address of the Rock Pi S board? You can see that on the phone under BT -> AAWireless -> Setting cog.

**Comment by tallLeRoy** [comment]
my Samsung S9 mac is A4:07:B6:E7:70:C5
the Rock Pi S mac is 22:22:C1:D9:4F:C4        The Samsung would not show it, used the Moto

**Comment by borconi** [comment]
Thanks.
Will work on this tomorrow, hopefully we will be able to update the image
tomorrow for further testing.

Kind regards
Emil Borconi-Szedressy
Tel: +44-791-32-32-588 / +40-755-29-00-43

**Comment by tallLeRoy** [comment]
This is the log from the hand modified image on Aug 17.

[putty.log](https://github.com/Snirpo/aawireless-issues/files/5086513/putty.log)

**Comment by tallLeRoy** [comment]
bug resolved with aawireless-22-08-stable
