### ISSUE TITLE
No start button on AAWirelessTester app 

### ISSUE THREAD

**Issue by Aauserlf** [Snirpo/aawireless-issues#14]
**Describe the bug**
When I open the Aawirelestester app a black screen comes up but then quickly it turns white with the text "Hello World!" and there is no start button anywhere and there is no tasker bootstrap task either.

**Screenshots**

**Car (please complete the following information):**
 - Manufacturer + type
2019 Nissan Leaf SL Plus

**Headunit (please complete the following information):**
 - Manufacturer + type
2019 Nissan Leaf SL Plus

**Smartphone (please complete the following information):**
 - Device: Samsung Note 8
 - Android version
Android 9

**Additional context**

**Comment by ilker-aktuna** [comment]
I have the same result on AAWirelessTester app.

**Comment by Aauserlf** [comment]
It seems there are several users with the same problem, but this was opened over 5 days ago and it looks like nobody can fix it, so I will close it now.

**Comment by Snirpo** [comment]
We can fix it :) But we mainly use the official bt bootstrap way right now. I'll update the readme.

**Comment by Aauserlf** [comment]
But how come you didn't say so sooner?  It's been almost a week since I opened this issue and you're commenting now after I close it?

**Comment by Aauserlf** [comment]
and by the way, the bluetooth isn't working for me either.
