### ISSUE TITLE
MMI no longer connects to AA with current image

### ISSUE THREAD

**Issue by mseifert9** [Snirpo/aawireless-issues#16]
**Describe the bug**
BT connects, WiFi connects, Searching for AA, then green light goes off and on. Process starts over.

**Screenshots**

**Car (please complete the following information):**
2018 Audi SQ5

**Headunit (please complete the following information):**
 - Audi MMI

**Smartphone (please complete the following information):**
 - Samsung Galaxy S10+
 - Android version: 10

**Additional context**
Last GOOD image with fully functional AA and MMI
 Image: dated August 27 and labeled wifi-hotspot-fixes
aawireless binary: dated August 31 and labeled "no setup mode, with usb retry" which you sent to me privately (edited)

**Comment by Snirpo** [comment]
Emil is creating a new binary which might fix stuff :) He will contact you on Slack.
