### ISSUE TITLE
Vehicle does not start AA - Jeep Compass 2018

### ISSUE THREAD

**Issue by ilker-aktuna** [Snirpo/aawireless-issues#18]
**Describe the bug**
After I connect to wireless AP of the device, I start AA on the phone using tasker task.
AA icon does not appear on car head unit. And nothing happens on car head unit.
on my phone's AA settings , wireless AA is enabled.
If I use the same USB cable to directly connect my phone (wired to car HU) , it works.
So the cable is OK. 

**Screenshots**

**Car (please complete the following information):**
Jeep Compass 2018 1.4 limited

**Headunit (please complete the following information):**
Uconnect 8.4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10+
 - Android version 10

**Additional context**
Tried removing all previous car connections from AA. Did not change the situation.
I also tried the app on Google Drive (WirelessAATester)  instead of tasker task. But there is no start button on the app.

**Comment by tallLeRoy** [comment]
If the current build has an issue with UConnect contact Chiel in the Slack channel, he may be working on it already.

**Comment by ilker-aktuna** [comment]
where is the  Slack channel ?
I was accepted to the beta later and I don't have much information about communication channels.

**Comment by tallLeRoy** [comment]
I have asked Emil or Chiel to send you the Slack info. Emil is on vacation this week, so if Chiel can't do it, it may take a while.

**Comment by ilker-aktuna** [comment]
maybe I should collect some logs. But I don't know how to do that...

**Comment by tallLeRoy** [comment]
The easiest way if you have Windows is to use Linux Reader by DiskInternals it is a free Linux EXTx file reading program for windows. 

Attach just the micro SD card to computer like you did when you burned it. Open Linux Reader and navigate to /var/log on the card. Select syslog and the Save in the upper icon bar. Save the file to your computer. Rename the file with the name of the build you are using and the symptom you are having. Then upload the log to  

https://drive.google.com/drive/folders/1yqNEI25MbO3XYHXm9qs_U8vUIbIrimo2

You might look up the format people use for the name on that site. Then send an email to Emil and Chiel to let then know you have posted a log. When you have Slack use that to notify them.

**Comment by ilker-aktuna** [comment]
well I already have other linux installed servers. if it is just the syslog file needed, I can post it.
But maybe it is not required. Let's wait for Emil or Chiel's instructions.

**Comment by ilker-aktuna** [comment]
Btw, because of the old Readme, I tried using the Tasker method. Now the readme says "use BT method". Should I try it  ? I assume it will not make any change because it seems that my car HU does not detect the device. But in any case, I can try...

**Comment by ilker-aktuna** [comment]
this issue seems to be caused by a problem in the recent release. 
using a previous version (from Sep. 2nd - bootloop  fix image) Jeep Compass Uconnect 8.4 works fine.
