### ISSUE TITLE
Android phone loses internet connection when connected to Wifi of Rock Pi S

### ISSUE THREAD

**Issue by ilker-aktuna** [Snirpo/aawireless-issues#19]
**Describe the bug**
When I connect my phone to Rock Pi S wireless AP, my phone loses internet connection.
If I force the mobile data , then wireless connection is lost.
There must be a way of running wifi for AA and mobile data for internet. Am I wrong ?
How can I make this setting ?

**Screenshots**

**Car (please complete the following information):**
Jeep Compass 2018 1.4 limited

**Headunit (please complete the following information):**
Uconnect 8.4

**Smartphone (please complete the following information):**

Device: Samsung Galaxy Note 10+
Android version 10

**Additional context**
Maybe rverse connection should be an option (rock pi connected to phone instead of phone connecting to Rock Pi)

**Comment by tallLeRoy** [comment]
I did some experiments with my Samsung Galaxy S9 this morning. It never failed to use the cell radio for internet data. 

I turned on this setting  Settings->Connections->WiFi->Advanced (Advanced is in the menu pull down with the three vertical dots in the upper right) I have 'Switch to mobile data' enabled in the Advanced menu.

**Comment by tallLeRoy** [comment]
Is there an app on your phone that manages mobile data? Maybe that is keeping it off when connected to AAWireless

**Comment by ilker-aktuna** [comment]
if I select "switch to mobile data" , then the phone identifies wifi as "connected without internet" and then closes wifi connection.
At least I don't see the wifi symbol on action bar, is it still connected ?

**Comment by tallLeRoy** [comment]
You should see if the WiFi is on with Settings->Connections->WiFi after you are connected to the device

My other selections in the Advanced menu are:

Turn on Wi-Fi automatically enabled
Detect suspicious networks enabled
Wi-Fi power saving mode disabled
Network notification disabled
Hotspot 2.0 disabled

There is also a sub menu if you click on Switch to mobile data
My Network exceptions are none  you may want to add the AAWireless network here
Allow individual apps to switch disabled  you may want to try enabling that so that Android Auto can trip it

**Comment by tallLeRoy** [comment]
What is your Slack name?

**Comment by tallLeRoy** [comment]
I just saw that Samsung has something called WiFi Security which I do not use. Is that enabled on your Note? Maybe an exception needs to be made for AAWireless. It would be a pain as the SSID changes with each build.

**Comment by ilker-aktuna** [comment]
>>You should see if the WiFi is on with Settings->Connections->WiFi after you are connected to the device

There I see the wifi as "current network" 
does that mean it is connected ?
I can't verify if it is connected or not because my car head unit does not do anything (see the other issue I've opened)

**Comment by tallLeRoy** [comment]
If is says AAWireless-***** in current network you are still connected to the AAWireless device via WiFi. The bluetooth connection should have dropped off. 

Now try to open an app that uses the internet.

**Comment by ilker-aktuna** [comment]
it works. I have internet connection over mobile data.
I just can't verify if wifi is still connected. But if you say "current network" means "connected" , that' ok.

**Comment by ilker-aktuna** [comment]
thanks for the help.
now , if I can get help on the other issue. how to troubleshoot.

**Comment by tallLeRoy** [comment]
close the issue when you are sure that it is working

**Comment by ilker-aktuna** [comment]
I will not be sure until I can get connection on car HU.
But let's close it anyway. Not to see unnecessary issues on board.
