### ISSUE TITLE
Uconnect and AAW loses connection after a couple of days

### ISSUE THREAD

**Issue by pdanders11** [Snirpo/aawireless-issues#22]
**Describe the bug**
After running AAW multiple days, sometimes the interface between AAW and the HU appears to go dead requiring forgetting device in HU and re-setup.  When in this mode restarting the phone or AAW doesn't seem to help.  Everything on the phone appears good.  Phone is searching or thinks car is attached.  Acts similar to original issue getting Uconnect to work in the first place.  HU just doesn't kick in.

**Screenshots**

**Car (please complete the following information):**
 Jeep Grand Cherokee 2018

**Headunit (please complete the following information):**
 - Uconnect 8.4

**Smartphone (please complete the following information):**
 - Samsung Galaxy S10e]
 - Android version 10

**Additional context**
It seems to take a day or two to occur.  I'm not driving daily so not exactly sure but it seems like some sort of idle time causes the interface not to respond

**Comment by KNON2000** [comment]
I am seeing the same issue with the 12" Uconnect on the 2020 Ram. 
Weird but most likely just a coincidence, I no longer get text notifications on the screen? Assistant still works, as long as I have an antenna or have the RockPi close to the phone

**Comment by tallLeRoy** [comment]
I am seeing the same issue with 9/16 build after several days use. Tried changing to a different SD Card, did not help. Cleared Bluetooth and Wi-Fi history on phone did not help. I am trying Clear Cache for Android Auto on the phone side. Will report back after giving that a test.

**Comment by Snirpo** [comment]
@pdanders11 can you upload some logs in the drive when this happens? Can you also validate the phone connects to the wifi of the board when this happens?

**Comment by tallLeRoy** [comment]
So I went a bit farther on the phone side. I cleared the AA data cache, forgot my Head Unit. Head unit forced USB connection first. After that, AAWireless was back to normal well behaved operations. No audio dropouts or lag.

**Comment by KNON2000** [comment]
Okay, I did the same thing as well. Removed all associations with the phone and rockpi. Removed the phone and rockpi from the HU projection manager and also removed the bluetooth pairing with the pickup. Rebooted phone and went back thru AA setup. Guess I'll know in a couple days if all is well :)

**Comment by KNON2000** [comment]
HMM, can't seem to get it to connect with the HU - the phone isn't autostarting AA when it connects to the RockPi bluetooth?

**Comment by KNON2000** [comment]
Wondering what settings I mucked up when I cleared the cache and data for AA on the phone?

**Comment by tallLeRoy** [comment]
KNON2000 watch your phone when you connect there are a couple of screens you need to answer. Also my head end wanted me to connect with USB before it would let AAWireless connect.

**Comment by KNON2000** [comment]
It worked fine via USB, going to walk thru it again

**Comment by KNON2000** [comment]
Not sure what's going on, for some reason it isn't activating AA when it connects to the Rockpi bluetooth, then the phone connects to the wifi - and the HU doesn't see it.  Works perfect when connected via USB. Cleared cache and data again and started over, same thing. Weird. I think I need to step back from it a bit

**Comment by pdanders11** [comment]
> @pdanders11 can you upload the syslog of this situation in the drive? Can you also validate the phone connects to the wifi of the board when this happens?

Yes the phone connects and wifi.  The Bluetooth connect to WiFi launch looks good.  Erased and reconnected several times and nothing seemed to kick the HU.  Phone is just stuck looking or thinks it connected.  Ill pay closer attention next time.  

I cleared the HU yesterday so I will pull logs next time.  Since yesterday, board appears to have power most of the time.  I just logged in and uptime was only 37 minutes so power was reset to the unit but restored after I turned off ignition.  So I don't expect to see an uptime of of 2 days now but I know module is alive most of the time as Bluetooth is asking if I want to connect which triggers wifi connect.

**Comment by pdanders11** [comment]
log uploaded

**Comment by borconi** [comment]
Is this still the case with latest images?

**Comment by KNON2000** [comment]
I had that happen with the 11/23 image - where I had to delete it from the HU - unplugging the unit and allow it to reboot then it came back up.
Kevin Cap

________________________________

**Comment by pdanders11** [comment]
> Is this still the case with latest images?

Yes, I'm still seeing this.
