### ISSUE TITLE
Google Assistans query window stays open

### ISSUE THREAD

**Issue by myhrmans** [Snirpo/aawireless-issues#23]
**Describe the bug**
Google Assistans query window stays open after a query. 
Pressing outside the query makes it disappear

**Screenshots**
![IMG_20200926_130312](https://user-images.githubusercontent.com/14261388/94361177-afe2ff00-00b2-11eb-94a7-80fd021acca7.jpg)

**Car (please complete the following information):**
 Renault Zoe ZE50

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 pro
 - Android version 10

**Comment by borconi** [comment]
Is this still an issue with the production version or it can be closed?

**Comment by myhrmans** [comment]
Issue has been resolved.
