### ISSUE TITLE
Music cuts out

### ISSUE THREAD

**Issue by myhrmans** [Snirpo/aawireless-issues#24]
**Describe the bug**
Playing music from spotify cuts out the playing music for halv a second then reconnects with a lower volume. Happens once every 2min

**Car (please complete the following information):**
 Renault Zoe ZE50

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 pro
 - Android version 10

**Comment by borconi** [comment]
Is the problem still present on latest image (30.10.2020 ? )

**Comment by myhrmans** [comment]
Not an issue today. Closing.
