### ISSUE TITLE
Interface is laggy in the first 1-2 minutes

### ISSUE THREAD

**Issue by Jefrimm** [Snirpo/aawireless-issues#25]
In the first 1-2 minutes after connecting, the interface is laggy. It responds slower to touch, and the animations are not so smooth. After that, it works perfectly! 

Car: Nissan Leaf 2020 Tekna 40kWh
Smartphone: Samsung Galaxy S20+ with Android 10

I have tested with the same phone and the same RockpiS on the Hyundai Kona, where this problem does not occur.

**Comment by tallLeRoy** [comment]
Can you copy the settings in /etc/aawireless/config.ini please.  That may give a hint.

**Comment by borconi** [comment]
@Jefrimm - Is this still an issue with latest image? The one from 30.10.2020?

**Comment by Snirpo** [comment]
Is this still an issue on the latest image from 3/12?
