### ISSUE TITLE
Won't reconnect after being away for a short time

### ISSUE THREAD

**Issue by tallLeRoy** [Snirpo/aawireless-issues#26]
**Describe the bug**
image from 9/16

Had a good solid connection, stopped the car powered off head unit, USB was still powered. Got back in started car, AA icon on Head unit was active. Select icon, black screen and audio would not start. Seems the phone connection was broken and did not start, but the connection from AAWireless to the head unit was still active.

**Screenshots**

**Car (please complete the following information):**
 - 2020 Hyundai Palisade

**Headunit (please complete the following information):**
 - Manufacturer + type

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - Android version 10

**Additional context**
This was working in prior images.

**Comment by tallLeRoy** [comment]
Verbose logging was disabled. Here is the contents of config.ini

[General]
Passthrough=true
[Hacks]
Dpi=0
RemoveTap=false
DeveloperMode=false
AudioSink=true
[Wifi]
Hotspot=true
Device=wlan0
IpAddress=10.42.1.1
Port=5000
SSID=AAWireless
Passphrase=0123456789
[USB]
ForceConnect=false

**Comment by Snirpo** [comment]
Seems a bit related to issue https://github.com/Snirpo/aawireless-issues/issues/27

**Comment by tallLeRoy** [comment]
The October 7th build has cleared the issue. Meet the failing conditions several times and it reconnected successfully each time.
