### ISSUE TITLE
2016 Chevrolet Corvette Z06 - Intermittent success at connecting successively

### ISSUE THREAD

**Issue by scrampker** [Snirpo/aawireless-issues#27]
**Describe the bug**
While the phone pairs to the car on initial attempt, and many times after I get into the car, without issue, I do run into problems where the phone simply does not connect when I hop in and start the engine... or if the car was running and I walk away with my phone. When this happens, I can sometimes get things to reconnect by unplugging the RockPiS, or by cycling Wi-Fi/BT on my Pixel 4 XL. Sometimes I eve have to power-cycle my Pixel 4 XL. For what it's worth, I even factory-reset my Pixel 4 XL (Android 11 Official ROOTED MAGISK,) because I was skeptical that there might be a problem with my device.

**Screenshots**
N/A

**Car (please complete the following information):**
2016 Chevrolet Corvette Z06 3LZ

**Headunit (please complete the following information):**
Factory headunit, (AC Delco?) with the 2017 software update which adds Android Auto, on top of prior CarPlay functionality.

**Smartphone (please complete the following information):**
Google Pixel 4 XL
Android 11 Official
Rooted via Magisk Canary

**Additional context**
In these scenarios I ensure that my device does not have a full filesystem due to logs, as I know that can be a source of failure. It's also noteworthy that the bootstrap process overall is not as fast as it was with previous versions of the board images. It's not that bad, at around 30 seconds, but it's worth noting. On older versions, as soon as BT connected, I would see the Wi-Fi handover, and my phone would vibrate. That takes 5-10x longer than it used to. My suspicion is that the timing of the board turning on when I open the car causes an issue when I start the car's engine (sometimes.) It might depend on how far my phone gets in the bootstrap process before the engine is started. I've not noticed a device power cycle when cranking, but that doesn't mean the board is operating perfectly during that condition. Perhaps the logs would indicate something. I definitely have major issues when I walk away into the gas station and lose connection to AAW. It can take me several minutes to reconnect, or many times I just plug the cable into my phone directly so I can drive off.

Logs located on Google Drive: https://drive.google.com/drive/folders/1_YeVLTflNn6VZK2o_mYYZE-hKdYauvVM

**Comment by Snirpo** [comment]
Huge log :) I'll check if I can extract these situations out of the logs.

**Comment by scrampker** [comment]
Yeah I hear ya!

I've got new logs from yesterday that are smaller and had repeated issues re-connecting. I think you may find them more useful.

https://drive.google.com/drive/folders/1L2DLfIuavUNx3ymyosqZlKHLW95Y6BjY

**Comment by scrampker** [comment]
Summary: While it connects sometimes, I had a bunch of re-connect issues. More often than not, it would not reconnect after quick stops in the car.

GitHub issue 27: https://github.com/Snirpo/aawireless-issues/issues/27 (added these new logs.)

Test configuration:
- /etc/aawireless/config.ini forceconnect false
- 2016 Chevrolet Corvette Z06 3LZ
- Powered solely from USB-C, no aux power needed.
- Pixel 4 XL, running Android 11 OFFICIAL. Rooted with Magisk Canary.
- “Wireless AA enabled” in AA, latest update of AA that came out today.
- Not using APK-method any longer. Only BT bootstrap.
- Board does NOT reboot during engine crank.
- USB power is introduced when door is opened. (Retained Accessory Power.)

In-Vehicle Testing:
What I am seeing is that when I stop at the gas station or store, and if I do not power off the car and allow the board to turn off completely, I run into issues re-connecting. This requires unplugging the board and/or disconnecting Wi-Fi/BT. I've noticed that sometimes I have to do a combination of all 3 things, because simply toggling BT/Wi-Fi does not always force a new bootstrap. Then even when bootstrap happens, it doesn't always re-connect to the headunit in the car. If I unplug ALONG with those radio toggles, it almost always come back up.

**Comment by scrampker** [comment]
Added results from 10/1 image:

https://drive.google.com/drive/folders/11VdSfLS_KQ2X7YlrxGYxY12zi2RFbR6h

Summary: Lots of issues pairing. Reconnects seem better on 10/1 build.

GitHub issue 27: https://github.com/Snirpo/aawireless-issues/issues/27 (added these new logs.)

Test configuration:
- Configuration app, various settings, noted throughout the details below. (MTP default is the only one the reliably works.)
- 2016 Chevrolet Corvette Z06 3LZ
- Powered solely from USB-C, no aux power needed.
- Pixel 4 XL, running Android 11 OFFICIAL. Rooted with Magisk Canary.
- “Wireless AA enabled” in AA, latest update of AA that came out today.
- Not using APK-method any longer. Only BT bootstrap.
- Board does NOT reboot during engine crank.
- USB power is introduced when door is opened. (Retained Accessory Power.)

Key Information:
- PDNS: When hitting the 'Projection' icon on the headunit home screen, it either response with "Projection Device Not Supported," or does absolutely nothing. Normally when it does nothing, this is when it's sending the signal to the phone and waiting. If this works, it will bring up the wizard or trigger the black-sliding-screen, which gets AA going.
- PJNOPE: When pushing the projection button and nothing happens. No wizard on phone either.
- Engine was not running. Rebooting headunit means I push ignition button and open the door. Screen goes blank. May or may not be fully rebooting the actual operating system.
- "Full unpairing," means I go into phone AA app to forget all cars, forget all BT devices on phone, then go over to the HU to forget the BT for my phone, as well as the Android Auto pairing. Full reset, other than the board settings.
- Regarding menu/active/add device. There's an deeply-nested Android Auto settings page on the headunit where you can add/remove AA devices, and see if they are active/not-active. I use this to see whether the board and the car are communicating properly, even if the homescreen projection icon does not light up.
- Unless otherwise noted, boostrap worked fine. Sometimes I point out when bootstrap connects to wrong wifi, or has other issues.


In-Vehicle Testing:
- FULL UNPAIR. Power on board, turn on HU. Didn't properly connect/bootstrap after pairing BT from phone to board.
- Reboot board. Bootstrap MUCH faster now. PDNS.
- APP:PASS-THRU. PDNS.
- Reboot phone. Reboot board. Connected BT but no bootstrap.
- Reboot board. Bootstrap worked this time. No AA icon in car. Unit shows not active on HU menu.
- APP:Direct Accessory. Reboot board. No success.
- Delete AA from HU. Reboot board. Nothing. No add device.
- APP:MTP retry. Reboot board. No add device.
- APP:USB not set. Reboot board. No add device.
- APP:MTP Accessory. Reboot board. Add device available. Activate. Shows not active on HU. Still connected BT and WIFI. PJNOPE.
- Reboot board. No active. No wizard. PDNS.
- Removed AA pairing from HU. Reboot board. No add device.
- Reboot board. No add device.
- APP:USB not set. Reboot device. No add device. 
- APP:mtp accessory delay. Reboot board. No add device.
- Reboot board. No add device.
- APP:MTP accessory retry. Reboot board. Add device shows up, then disappears quickly. Does not re-appear.
- APP:MTP accessory delay. Reboot board. Add device shows up, then disappears quickly.
- APP:MTP Accessory. Reboot board. Add device works, and stays.
- APP:Direct accessory. Reboot board. No add device. 
- APP:MTP accessory. Reboot board. No add device. 
- Reboot board. No add device.
- APP:USB not set. Reboot. No add device. Reboot. No add device.
+ APP:MTP accessory. Reboot. No add device. Reboot. Yes add device. Paired on HU. Wizard appeared on phone. Connected. Waze error, so I killed wifi bt to check. No problem with Waze on the phone.
- Reboot board. Bootstrap isn't getting me into wifi any longer.
- Reboot board. Still not on the right wifi. 
- Pulling board power. Bootstrap worked this time. No AA icon on HU. Not active in menu.
+ Reboot HU. Reboot board. AA icon okay. I'm in AA just fine. Some audio skipping.
+ Reboot board. AA drops immediately. Came back just fine after 30s. Some audio skips.
+ Toggle wifi/bt. Bootstrap worked and I'm back in.
+ Reboot HU. AA came up instantly.
- Delete AA and BT on HU. Forget cars app. Forget all BT on phone. Reboot board. Accept pairing on BT. Did not show add device on HU.

***Setting debugging via app.***

- Reboot board. Bootstrap failed to connect proper wifi. 
- Reboot board. Bootstrap okay. Add device shows. Ack on HU. Device shows not active on HU. No wizard on phone. Still on wifi bt.
- Reboot board. Bootstrap. No wizard. PJNOPE.
- Reboot board. Bootstrap. No wizard. PJNOPE.
- Reboot HU. Leaving board online. Still on WIFI and BT. PDNS.
- Reboot board. Bootstrap. PDNS. Not active. 
- Pulling board power. PJNOPE.
- Rebooting phone. Pulling power on board. Powering off HU. Powering on board+HU at same time with ignition button. BT connected, but no bootstrap to wifi. 
- Rebooting board. Bootstrap okay. No wizard. PDNS.
- Fully unpairing. Pulling power on board. Accept pair from board. Yes contacts. Bootstrap okay. Add device. Ack on HU. Device not active in nenu. No wizard. Tap projection on HU, no error, no wizard.
- Reboot HU. Pull power on board. Wait HU come up. Plug in board. PDNS. 
- Toggle BT Wifi. PDNS. Not active.
- APP:USB not set. Reboot board. PJNOPE. Not active. 
- APP:MTP accessory. Reboot board. PDNS. Not active. 
- Reboot HU. Leaving board connected. PDNS.
- Pull board power. PDNS. No wizard. 
- Unpair AA from HU menu. Reboot HU. Pull power on board. Wait for HU. Power on board. No add device.
- Reboot board. No add device.
- APP:USB not set.

**Debugging showed disabled!! Changed again...**

- Reboot board. No add device. 
- APP:MTD accessory. Debug was disabled again!!
- Reboot board. No add device. 
+ Reboot HU. Reboot board a few sec later. Add device YES. ACK HEADUNIT. No wizard.
+ Reboot board. PJ button brought up wizard!!! 
- Unplug board. Unpair everything. Leave HU on. Power on board. Accept pair request on phone. Bootstrap did not happen. BT did not stay connected.
- Reboot board. Reboot HU. No add device. 
- Reboot board. Add device yes. Ack on HU. PJNOPE. PJNOPE again.
- Reboot board. Wait 5s, click PJ. Wizard appears. AA is functional again. Unplugging to grab logs.

**Comment by Snirpo** [comment]
Holy! That's alot of info. Well few things I can extract from this without reading the logs is:

- WiFi hotspot is funky sometimes. This is a known problem. Haven't yet found out why this is happening.
- Your car only works in MTP to acc mode. This is what we expected.
- The initial pairing with the HU is problematic. I've seen this before on other cars as well. Wizard sometimes does not show. I've seen this happening as well. Not sure if this is an AA or AAW issue.
- There are some bugs with saving the settings from the app

**Comment by scrampker** [comment]
Yup, I'd say the biggest issue to overcome right now is the finicky pairing process. Once that's flawless, we can look at walk-away/reconnect problems.

**Comment by scrampker** [comment]
Summary: Could not get the board+phone+HU fully paired.

Logs added here: https://drive.google.com/drive/folders/16bOwU93P9me4g1Z5SjNF-3bB7_IO1ISK

Test configuration:
- Configuration app will not start. Manually enabled debug in config.ini.
- 2016 Chevrolet Corvette Z06 3LZ
- Powered solely from USB-C, no aux power needed.
- Pixel 4 XL, running Android 11 OFFICIAL. Rooted with Magisk Canary.
- “Wireless AA enabled” in AA, latest update of AA that came out today.
- Not using APK-method any longer. Only BT bootstrap.
- Board does NOT reboot during engine crank.
- USB power is introduced when door is opened. (Retained Accessory Power.)

In-Vehicle Testing:
- Unpaired in all directions, including AA app.
- Pair phone to board.
- Bootstrap worked okay.
- "Add device" showed up in headunit AA nested menus. 
- Confirmed 'dangers' on vehicle headunit screen.
- No action on phone.
- Reboot board several times. Still no wizard on phone after bootstrap.
- Reboot phone. Still no AA wizard.
- Plug USB directly into phone and works fine.

**Comment by Snirpo** [comment]
This is still an issue with the new board I suppose?
