### ISSUE TITLE
Improve UX by separating out "Select & Connect" before the options.

### ISSUE THREAD

**Issue by daverein** [Snirpo/aawireless-issues#28]
I would have a 'select and connect' dialog/activity before showing the actual options, and then only show the options once properly connected.  Similar to ODBII apps (or at least the one I use - ODBLink).  UX is currently a bit non-intuitive, IMHO, all combined.  Also, I dont *believe* that the material design floating action button is appropriate to use for "Exit/End" as they should generally be used for the common actions of the screen (ie Save).  Again, all just MHO...

**Comment by Snirpo** [comment]
We are completely rewriting the app with a way better UI :)
