### ISSUE TITLE
Flashing Green Power Light on Connection

### ISSUE THREAD

**Issue by dawnofwar911** [Snirpo/aawireless-issues#3]
**Describe the bug**
When connecting the ROCK PI S to the vehicle the green power light on the board blinks instead of staying solid and the device is not discoverable by bluetooth or is transmitting the wireless signal.

**Screenshots**
N/A

**Car (please complete the following information):**
 - Ford Puma 20.25My

**Headunit (please complete the following information):**
 - Ford Sync 3

**Smartphone (please complete the following information):**
 - Samsung Galaxy S10/Pixel 4XL
 - 10/11 Beta 3

**Additional context**
I suspect the issue is caused by the fact that the Puma is not providing enough power to the Rock PI. I have tested in another vehicle and the board will at least connect. There is a general voltage difference in the 2 cars main 12V voltage rails, but i do not have a USB voltage reader to provide the details on what the USB ports are putting out.

**Comment by borconi** [comment]
Try a few more different USB cables. We just did some readings and the board in idle is not using more then 0.14A (140mA) which is way below the 500mA every USB port will provide. Also did a bit of research and based on the board manufacturer comment: https://www.cnx-software.com/2019/07/31/buy-orange-pi-zero-lts-sbc/#comment-565131 the board power usage should be really really low, like 50mA in idle stat.

**Comment by dawnofwar911** [comment]
Thanks, will give a few more wires a go. I've tried with 2 so far but no luck in any of the usb ports on the vehicle.

**Comment by dawnofwar911** [comment]
Tried 3 different USB wires today, all of which i know work correctly to charge my phone and work when used on the PI in another vehicle. I may have a Micro USB to USB-C i can try, but otherwise not sure on the next steps here. Also have noticed that the USB port by the center console has stopped working on any device. Not sure if it's related, but i have only used the car to test with the PI since i started yesterday. Am hoping a sleep cycle in the car recovers it.

**Comment by borconi** [comment]
This is a very strange one.... I've got confirmation from the board manufacturer that the device should work fine with 300mA so well below the 500mA provided by any USB port. 
I'm using a USB power meter myself this morning and the power draw is about 0.09A on idle, 0.11 when AA is running and the max spike I saw was 0.42.

On the other hand when I inserted the power meter to my laptop and the board to it, the board wasn't able to boot up and the power meter kept resetting itself, which is a very strange behaviour indeed.

**Comment by dawnofwar911** [comment]
I've bought a USB power meter myself to test the voltages on the two cars and compare. Has that green LED been configured to anything else in the image or is it purely device power? If there's no difference then is it possible that the car sees the device as something that is not supposed to be connected and is blocking it somehow on the data side of the connection?

**Comment by borconi** [comment]
Green is just power.
And device should not be visible as anything (invisible) maybe that is a
problem for some cars as the USB port id designed for data not power and if
the car does not detect anything on the data side it simply switches off
the port or resets it, trying to get some info from the device...
Do you have anything which can be powered from USB but it's not a smart
device, just plain power to test if that works on the car?
On the other hand I know that Ford Sync 3 units are pretty forgiving.....

Kind regards
Emil Borconi-Szedressy
Tel: +44-791-32-32-588 / +40-755-29-00-43

**Comment by dawnofwar911** [comment]
I have some wireless headphones which the case is charged by USB-C which should suffice. When just providing USB power and not via USB-C charge at least flows to this little toy drone battery i have. If i can find my adaptor that i had i'm going to try and see if it at least allows the board to boot correctly if i use micro-USB to USB-C connector.

**Comment by dawnofwar911** [comment]
Tested with the the headphones case which is charged and the micro to usb-c adapter which i'm getting the same issue with. From the slack someone with another ford will be testing tonight to confirm whether it's a ford thing or unique to my particular car/sync version.

**Comment by borconi** [comment]
Do I understand correctly that when you plug in the headphone case to the Ford USB you are experiencing the same power cycle like you did with the Rock Pi S board?

**Comment by dawnofwar911** [comment]
Sorry, no, i probably could have worded it better. The headphones case charges as normal and its power light is consistant.

**Comment by Wouter0100** [comment]
Weirdly enough I also get power cycles when I run it from my laptop's USB ports, same as with the Ford Sync 3. It does boot when using my Oneplus wall adapter.

**Comment by dawnofwar911** [comment]
That's weird, when hooked up to anything but the ford mine is booting and is stable

**Comment by dawnofwar911** [comment]
Issue closed with the bootloop fix image from 04/09
