### ISSUE TITLE
Youtube Music Randomly Pauses

### ISSUE THREAD

**Issue by daverein** [Snirpo/aawireless-issues#30]
**Describe the bug**
While normal driving and playing music via youtube music (and maps or wazes being displayed), music will be randomly paused.  Sometimes a couple of times within a minute, but then just fine for 15+ minutes.
This is different from the other reported music issue.  The volume stays where it was.

**Screenshots**
(just a paused youtube music playbar)

**Car (please complete the following information):**
 - Porsche Cayman 

**Headunit (please complete the following information):**
 - Porsche PCM 4.0

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android version 11

**Additional context**
Only issue on newest beta (sept 30th)

**Comment by Snirpo** [comment]
Is this still an issue on the new board?

**Comment by daverein** [comment]
Nope, this has not happened for a while
