### ISSUE TITLE
Wrong wording in Experimental features > Developer Settings

### ISSUE THREAD

**Issue by SaulGoodman1337** [Snirpo/aawireless-issues#36]
**Describe the bug**
When activating the Developer Settings I get the wrong wording

**Screenshots**
https://user-images.githubusercontent.com/4953452/111308444-fa553980-865a-11eb-8fc0-15db491e6718.mp4

**Car (please complete the following information):**
 - Volkswagen Golf 7 GTD

**Headunit (please complete the following information):**
 - MIB2

**Smartphone (please complete the following information):**
 - Device: Oneplus 8 Android 11

**Additional context**
Activation works as expected. Here only the wording is not correct

**Comment by Snirpo** [comment]
Thanks for your report. We'll fix this in the next version (1.4.0) of the app :)

**Comment by Snirpo** [comment]
Fixed in 1.4.0, now available on the beta channel.
