### ISSUE TITLE
Vehicle Not Starting AA

### ISSUE THREAD

**Issue by dawnofwar911** [Snirpo/aawireless-issues#4]
**Describe the bug**
The phone and the Rock PI connect perfectly with the phone saying it's using the wireless connection for Android Auto, but the car does not trigger Android Auto.

**Screenshots**
Can be provided to show the connections is stable from the phone if necessary

**Car (please complete the following information):**
 - Vauxhall Corsa SE Premium 2020

**Headunit (please complete the following information):**
 - Vauxhall Intellilink (will try and find the version, cant find any info online)

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android 11 beta 3

**Additional context**
The infotainment system is fairly primitive and has previously been a bit finnicky when used with carplay. Tomorrow i will attempt a manual connection to the vehicle with just the wire and then retry the wireless connection.

**Comment by borconi** [comment]
If I know correctly on Intellink you need to switch it from CarPlay to AndroidAuto before you can use it, please do confirm that a direct cable connection between phone and car does actually work.

**Comment by dawnofwar911** [comment]
Ok, will give that a go when i have a chance tomorrow. It's not the most intuitive infotainment system i find the Vauxhall so will have a play with it.

**Comment by dawnofwar911** [comment]
I tried again this morrning and validated that i could connect with AA straight away without using the ROCK PI. When connecting with the PI my phone acknowledge it's connected, but nothing is displayed on the cars screen. Video attatched shows this and the connection process. 

https://photos.app.goo.gl/XEHcRc8m1FVbFDtT6

**Comment by borconi** [comment]
In the video it looks like the AA icon is actually activated on the car, what happens if you try to press it?

**Comment by dawnofwar911** [comment]
It just asks you to connect a device and enable AA as if i hadn't plugged anything it

**Comment by borconi** [comment]
Will update  image today with verbose debugging enabled that should help us understand a bit better whats going wrong.

**Comment by dawnofwar911** [comment]
aawireless log attatched with latest image and changes suggested from slack.

Times of connection was 13:25 and disconnect was 13:27, all in BST
[aawireless.log](https://github.com/Snirpo/aawireless-issues/files/5090371/aawireless.log)
