### ISSUE TITLE
VW unit resets

### ISSUE THREAD

**Issue by borconi** [Snirpo/aawireless-issues#42]
VW head unit reset when you unplug and re-plug the device. 
Mainly happens on quick consecutive action.

See: https://1drv.ms/f/s!Aur-fFLxhu8sscByO2tYUOwL12eqBg

**Comment by Snirpo** [comment]
VW also resets when playing music.

**Comment by Snirpo** [comment]
I see you have a Technisat unit. This is indeed a general issue on Technisat units. We can never completely fix it cause it's inherently an head unit issue. However we are trying to work around the issue. For a test you can disable the audio sink from the companion app, this will get rid of the issue.

**Comment by Snirpo** [comment]
We found a solution, this issue will be fixed in 1.3.0.

**Comment by Snirpo** [comment]
Fixed in 1.3.0
