### ISSUE TITLE
Need constant USB toggling.

### ISSUE THREAD

**Issue by borconi** [Snirpo/aawireless-issues#43]
Probably car not sending USB Switch mode correctly.

I've found out that my car only works with Direct USB Mode.
My problem is that I can only get my car to "enable" AA when switching from direct to MTP and then back to direct, it seems that this change in mode enables my car to register the device the right way, and then it automatically launches AA on the screen.

If I unplug the AAW device and plug it back into the USB-port, I can see my AA icon on car screen is enabled, normally when clicking it, AA is launched, but nothing happens when doing so, even though the icon changes from greyed out to white as soon as the AAW has booted and connected to the phone, which indicates that the car does register the AA device, but can't negotiate with it or whatever... Only when toggling the USB mode as described above, AA is launched on screen.

The connection between my AAW and my phone is rock solid and established right way.

It can be really hard to get the AAW-app to communicate properly with the AAW, at most times the in app buttons are greyed out. I have to restart the AAW more than once in order to - with luck - change the host mode. I don't know why it is so hard to control the AAW from the app, but maybe this gets better as you develop the app.

See: https://cpeb.freshdesk.com/a/tickets/839

**Comment by tallLeRoy** [comment]
the user could try 'Request video focus on start' in AA developer settings as a work around
