### ISSUE TITLE
Landscape mode in AAWireless Config app

### ISSUE THREAD

**Issue by AndersWinther-Dahl** [Snirpo/aawireless-issues#44]
**Describe the bug**
When using the AAWireless Config app in landscape experimental features shows  although not toggled on, and Logout is hidden. 

**Screenshots**
![Screenshot_20210319-195317](https://user-images.githubusercontent.com/10073411/111829305-cb55f680-88ec-11eb-9161-0cd4e6cb485a.jpg)
![Screenshot_20210319-195643](https://user-images.githubusercontent.com/10073411/111829665-44ede480-88ed-11eb-95c1-2e2ec42a4efd.jpg)

**Car (please complete the following information):**
N/A

**Headunit (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
Oneplus 6
Android 10

**Additional context**
I would suggest that you drop support for landscape mode.

**Comment by Snirpo** [comment]
Completely agree, landscape mode will be gone in 1.4.0, which will probably be released today in beta.

**Comment by Snirpo** [comment]
Fixed in 1.4.0, released in beta right now.
