### ISSUE TITLE
Citroen C3 | Steering wheel controls not working

### ISSUE THREAD

**Issue by Limpperi** [Snirpo/aawireless-issues#45]
Steering wheel controls doesnt respond to anything at all.
MTP mode is not working with my hu, but direct is. Passthrough is disabled.

Car: Citroen C3 2020 (2017-2020)
Hu: OEM Bosch RCC 
Phone: Oneplus 7 pro running android 11

**Comment by borconi** [comment]
Does the problem persists with passthrough enabled as well?

**Comment by Limpperi** [comment]
Yes it does

**Comment by AndersWinther-Dahl** [comment]
Duplicate of #37?

**Comment by Limpperi** [comment]
Actually yes, i think that the 208 uses the same rcc headunit.

**Comment by Snirpo** [comment]
Yes issues seem to be related, I'll close this issue.
