### ISSUE TITLE
Jaguar iPace need to restart unit for it to work again.

### ISSUE THREAD

**Issue by borconi** [Snirpo/aawireless-issues#46]
I've spent the last part of the hour in the car and I've made some progress. The USB cable is not the issue, I've reproduced the below with the original cable as well with one of mine.
It looks like in order for AAW to work with the jaguar I-pace head unit, every single one of these conditions needs to be met:

1. It's critical that the radio is manually turned off before AAW/the phone disconnects; the disconnection happens either manually or when the door is open after the 'ignition' (in quotes because this is an electric car - by off I mean car shut down) is off. If the radio is left on, it will shut down itself when the door opens and the ignition is off, but AAW will fail to connect in the next round, and the AAW dongle will need to be disconnected from the cable, and then the car radio turned off.

2.When the head unit prompts how to handle the 'new android device', it shows 3 options: Android auto | In Control apps (a Jaguar proprietary app suite) | none. If any option other than Android Auto is selected, then AAW will fail to connect, the cable will need to be disconnected, the radio turned off, and the whole process needs to start again.

3. AAW will start at this stage - in one instance I had an issue with sound not playing and another with the bottom bar not loading. If I let an audio app (like Audible) turn on the radio from Android Auto and set it as source for the head unit, it seems to run fine.

4. Once done, this is where it's now critical to turn off the radio with the hardware dashboard button before exiting the car if one wants the AAW to connect the next time one gets into the car.

Disclaimer: I have yet to come back to the car after the computer has completely shut down to see if AAW connects straight away, there might be more to this. The fact that one has to manually select AA on the on-screen prompt defeats the purpose of AAW, and I'm not sure if there is anything you can do to fix the behavior - I strongly suspect it's a JLR (Jaguar Land Rover) specific behavior, the on-board software is extremely poor (specifically, and this could affect AAW, the software doesn't remember when I shut off the radio before shutting down the car, as on the next ignition, it turns it on automatically; plus a myriad of other settings that reset regularly).

Maybe in this case a disclaimer that the Jaguar I pace 2019 and 2020 (pre- Privi, the next generation of infotainment that the 2021 i pace comes with, that I cannot test as it's not retrofitted), may be advisable on your website...

**Comment by Snirpo** [comment]
Should be fixed with 1.4.0.
