### ISSUE TITLE
Phone will not connect to wifi server

### ISSUE THREAD

**Issue by dawnofwar911** [Snirpo/aawireless-issues#5]
**Describe the bug**
The phone and the Rock PI connect over BT fine and then the wifi connection is attempted but it is unable to form a propper connection and obtain an IP address

**Screenshots**
None available at the moment, but can be obtained to show WIFI screen and the "looking for Android Auto" bar in the notification centre.

**Car (please complete the following information):**
 - Vauxhall Corsa SE Premium 2020

**Headunit (please complete the following information):**
 - Vauxhall Intellilink (will try and find the version, cant find any info online)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - Android 10

**Additional context**
This seems similar to the issue originally reported over email where the BT connection is completed but the wifi connection will not fully go through.

**Comment by borconi** [comment]
This is under investigation, seems that there is some kind of weirdness with the AP on the board.. hopefully will have it fixed tomorrow.

**Comment by dawnofwar911** [comment]
Issue is resolved with the latest image, both my samsung and Pixel on varying android versions will connect to the device, just yet to get the device to talk to the vehicles i have.
