### ISSUE TITLE
Audio cuts out every ~10s

### ISSUE THREAD

**Issue by TherisaHaze** [Snirpo/aawireless-issues#51]
Every ~10 seconds the audio cuts/studders. Both with Spotify and YouTube (I listen to a news show).

No screenshots.

Volvo XC40 Recharge 2021, 

Original heading, 12.3" Display

- Sony Xperia 1 mk1 J9110
 - Android 11

**Comment by Snirpo** [comment]
If this is a second batch device, it's a known issue. I can put your device on 1.2.2, that should fix it. Please send me a PM on Slack (https://aawireless.slack.com/) if you want to test this version.

**Comment by TherisaHaze** [comment]
Backed i September, Initialy December delivery. That makes it 1st batch right?

**Comment by Snirpo** [comment]
Did it come with 1.0.0?

**Comment by TherisaHaze** [comment]
Yes. Updated directly to 1.2 (didn't have a car for a while).
I have tested som more. And sometimes Spotify works flawless, but if I turn on the screen of the phone, the studer starts. So listening to Youtube does always replicate the issue.

**Comment by Snirpo** [comment]
This sounds like a phone side issue. Do you have another phone you can test with?

**Comment by Snirpo** [comment]
@TherisaHaze Can I close this issue?

**Comment by TherisaHaze** [comment]
Yes. Thank you. The issue have faded in intensity. I'm about to get a new
phone, so if the skipping persists I will take it from there.

/Hasse

Den ons 26 maj 2021 22:12Chiel Prins ***@***.***> skrev:
