### ISSUE TITLE
Can't update OTA?

### ISSUE THREAD

**Issue by 88fingerslukee** [Snirpo/aawireless-issues#52]
The app refuses to update my device to 1.2.3. Keeps saying update failed. The device reboots but the update isn't applied. any ideas on what to do here?

I've tried resetting it, rebooting the phone, clearing storage and cache of the app.

**Comment by jamer007** [comment]
@88fingerslukee i had the same issue, version 1.1.0, with my phone (Huawei Honor 10), i tried with another android device (my tablet), and it works, i was able to connect and update the dongle to the 1.2.3.

**Comment by Snirpo** [comment]
There might be a problem with some Huawei phones, I'll look into it.

**Comment by 88fingerslukee** [comment]
Hey guys. Thanks so much for responding. I figured the issue out. It was my Adguard VPN. I didn't whitelist the AAW app! 🤦‍♂️🤦‍♂️ 

Anyway, hope this helps somebody else.
