### ISSUE TITLE
Steady communication loss - SEAT Leon 2019 & SAMSUNG Galaxy S21

### ISSUE THREAD

**Issue by Gorch25** [Snirpo/aawireless-issues#56]
**Describe the bug**
The device (AAW) boots and after short while the blue LED is permanently ON.
After - let's say 10 seconds, the AAW starts blinking green, the blue and then getting blue perm ON.
And again and again and again ...

**Screenshots**

**Car (please complete the following information):**
 - SEAT LEON Cupra ST - MY 2019

**Headunit (please complete the following information):**
 - VW/VAG MIB2

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21]
 - Android version 11

**Additional context**
- I must switch to USB Mode 'Direct' else no connection comes up
- The Tab on the car's head unit is not switching to 'Android Auto', stays at 'Mirror Link'
- On the Smartphone you can see that the WIFI connection AND the Bluetooth connection to the AAW disconnects and connects again and again and again...
- On the Smartphone you can see in the notifications that:
a) one connection to Android AUto is establishes
b) and another connection tries to connect to Android Auto...but never gets one!
- I reset the AAW device multiple times &  de-installed (with Cache Flush) and installed the AAWireless App multiple times with no result!

**Comment by Snirpo** [comment]
Please try to send some logs via the companion app and pass me your device name (AAWireless-xxxx). I'll look into it.

**Comment by Gorch25** [comment]
Thank you for your reply.
My device name is AAWireless-ZrKB8C.
I'll post you a Bug Report as soon as I have access to my car...

**Comment by Gorch25** [comment]
Hi.
The solution 'Acivate Wireless Projection in Android Auto Settings' and a higher (50.000) value for 'WIFI Timeout' did it for me.
Thanks for the help.
