### ISSUE TITLE
Keeps searching Android auto

### ISSUE THREAD

**Issue by jeronimow** [Snirpo/aawireless-issues#58]
**Describe the bug**
Android auto app on the phone keeps "searching Android auto" in my Opel Astra.
In my wife's car Seat Ibiza it works, but doesn't show up automatically on screen.

**Car (please complete the following information):**
 - Opel Astra K

**Headunit (please complete the following information):**
 - Opel intellilink

**Smartphone (please complete the following information):**
 - oneplus 7t (hd1903)
 - Android 11

In direct USB mode, several cables tried out.
Developer options wireless Android auto is enabled.

**Comment by Snirpo** [comment]
We have someone else with the same issue. Could you try the "MTP with retry" USB mode? Also could you post your device name (AAWireless-xxxx)?

**Comment by jeronimow** [comment]
This also doesn't work. Thé only way to get as far as possible is direct mode without passthrough. Then I'm able to get it ruikt connecties, but still searching. It Evens shows in devices on my car but not connected.
The device name is SNRkBqnw

![16208456558684746966001749648658](https://user-images.githubusercontent.com/83981577/118029214-3e677080-b364-11eb-91d5-fc0455241e46.jpg)

**Comment by Snirpo** [comment]
Well this is actually pretty good information. So there is connection with the car, but it just won't start. I'll look into it further.

**Comment by borconi** [comment]
Could be video focus on start is requested.

Zoltán will ask user to try that.

Kind regards
Emil Borconi Szedressy

**Comment by darmok911** [comment]
I have exactly the same problem.
The car is an Opel Insignia B, the headunit is Intellilink and the smartphone is a Oneplus 7 Pro with Android 11. 
The connection is stable only in USB Direct mode without passthrough (blue LED is static). On the smartphone now appears all the time "Android Auto is being searched". Nothing else happens. No Android Auto on the head unit.

**Comment by Snirpo** [comment]
@jeronimow I put your device on a beta version. Could you test? You can update via the OTA update screen. Please make sure the USB mode is on MTP.
@darmok911 Could you pass me your device name? I'll also put your device on the same version.

**Comment by darmok911** [comment]
My device name is AAWireless-hNUevGG1. I will test this and report back.

**Comment by Snirpo** [comment]
@darmok911 You should be able to update now. Please make sure to test MTP mode and MTP with retry. For the other modes there's no difference.

**Comment by jeronimow** [comment]
@Snirpo I just did the update, resetted the bluetooth connection. Connection phone to aawireless was ok. The connection between car and aawireless I had to do manually on the intellilink system. then it worked! Also the auto video focus works when activated!
Many thanks, now I can keep my second perk for our second car.

Ps. I saw the start/stop function and as option Opel Astra. In my Opel Astra the USB power goes off after 5 or 10 minutes. Does it have an advantage to enable this function?

**Comment by darmok911** [comment]
It works for me now too. The USB mode is set to MPT. The setup process now ran flawlessly and Android Auto is now usable on the headunit. Also, the automatic restart in the morning works great and Android Auto is immediately on the screen. Thank you!

**Comment by Snirpo** [comment]
Fixed in 1.4.0

**Comment by PK-19-88** [comment]
Hi Snirpo,
i find you on Github.
I think i have the Same Problem Like this Guys.
My Device Name ist, 27fd8nKm .
I Hope u can help me.
Kind regards
