### ISSUE TITLE
Head Unit does not recognize attached device

### ISSUE THREAD

**Issue by mseifert9** [Snirpo/aawireless-issues#6]
**Describe the bug**
AAWireless paired via bluetooth and connects to phone's wifi. AA automatically loads on the phone. Head Unit does nothing. After AA loads, within 20 seconds, the phone screen flashes black for a second and the AA screen returns to the phone.

**Details**
- I needed to set up the wifi connection using a static IP. DHCP gave the error "Couldn't get an IP address". After the connection, it says, "Connected without Internet" (I live in a remote location).
- AAWireless paired to the phone via bluetooth, but AAWireless-zkxyh58B does not say "Connected" (not sure if it's supposed to).

_AA settings:_
 - Accepted Cars: Audi
 - Autolaunch Devices:  Audi MMI and AAWireless-zkxyh58B
 - Use Bluetooth - ON (I tried off as well)
 - Wireless Projection - ON

**Other Notes**
- -Audi MMI shows "Audi Smartphone Interface" instead of the Android Auto symbol shown when wired. 
 - When "Audi Smartphone Interface" is manually selected, it gives the message, "To use Apple CarPlay or Android Auto, please connect a compatible smartphone using the USB port. Then activate your device in the settings for connected devices." AAWireless is not shown as a device under any of the settings.

**Screenshots**
![20200816_202022](https://user-images.githubusercontent.com/20809254/90362747-30273680-e016-11ea-8ed8-d888ee7928c4.jpg)
![20200816_202054](https://user-images.githubusercontent.com/20809254/90362748-30bfcd00-e016-11ea-9b6e-5a70be9cd808.jpg)
![Screenshot_20200816-202345_Settings](https://user-images.githubusercontent.com/20809254/90362752-31586380-e016-11ea-947b-62fc9adef107.jpg)
![Screenshot_20200816-202408_Android-Auto](https://user-images.githubusercontent.com/20809254/90362756-31f0fa00-e016-11ea-9cbb-9682efa1acc9.jpg)

**Car (please complete the following information):**
 - Audi SQ5

**Headunit (please complete the following information):**
 - Audi MMI

**Smartphone (please complete the following information):**
 - Samsung Galaxy S10+
 - Android version: 10

**Additional context**
First time running. I made sure AA worked via USB before testing.

**Comment by borconi** [comment]
Turn off auto launch on Bluetooth inside Android Auto please. It generates
a race condition, you should not have Android Auto running on the phone
screen at all.

Kind regards.

**Comment by mseifert9** [comment]
Thanks for the quick reply. I disabled Autolaunch in AA. The phone connects to the AAWireless via wifi, but nothing happens after that either on the phone or the MMI Head Unit. 

I realize I am confused what the purpose of the bluetooth connection to AAWireless is. They are paired but I don't see an active connection taking place, or anything beyond the wifi connection.

**Comment by borconi** [comment]
Try to reboot the board, it works on a one-shot basis it will try to connect to the phones BT on boot, once the connection is done the phone will try to connect to AAWireless Wifi and start Android Auto. Maybe monitor the BT setting on the phone. Sounds like on the first attempt you got that correctly but second one it's like the BT pairing did not happened.

**Comment by mseifert9** [comment]
I started fresh this morning and indeed the Bluetooth connected as well as wifi. However, still no luck with the MMI head unit. Nothing else happens.

**Comment by borconi** [comment]
Please check the updated image. Also you should have received a slack
invitation for chat.

If problem persists with todays image please pull the aawireless.log from
/var/log/aawireless.log

Kind regards.
Emil Borconi-Szedressy

**Comment by Snirpo** [comment]
I think we can close this one :)
