### ISSUE TITLE
Experimental features particularly the audio sync drop

### ISSUE THREAD

**Issue by ZoltanAndras** [Snirpo/aawireless-issues#64]
However it only works for music media ie Spotify/YT music.
Is there a way i can sync all sound via bluetooth ie google assistant and navigation apps?

**Comment by Snirpo** [comment]
Hmm, I don't really get this one? Can you explain?

**Comment by martinarmstrong123** [comment]
sounds as if he means the option 'disable audio sink' which only works for music apps and in that case is similar to my request for using bluetooth headset also for navi apps.

**Comment by Snirpo** [comment]
Yes indeed, same thing, closing this one.
